project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - lahti_bioc2023.qmd
    - hintikkaxo_presentation.qmd
    - intro.qmd
    - bioconductor.qmd
    - starting.qmd
    - reproducible_workflow.qmd
    - mgnifyr.qmd
    - miadash.qmd
    - datacontainers.qmd
    - data_manipulation.qmd
    - summarizedexperiment.qmd
    - day2.qmd
    - treese.qmd
    - tengeler2020_presentation.qmd
    - quarto.qmd
    - alpha_diversity.qmd
    - pcoa.qmd
    - dbrda.qmd
    - compositional_heatmap.qmd
    - differential_abundance.qmd
    - oma.qmd
    - gbcc2025.qmd
    - ismb_eccb2025.qmd
